name: Generate Release PDF
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Linear Algebra.tex
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Linear Algebra.pdf
